MODULES = binfilepy

# requirements.txt is generated by
# pipreqs .
init:
	pip install -r requirements.txt

clean:
	rm -rf ./.cache ./__pycache__ ./.pytest_cache
	rm -rf ./tests/.cache ./tests/__pycache__
	rm -rf $(foreach var,$(MODULES), ./$(var)/__pycache__)
	rm -rf $(foreach var,$(MODULES), ./$(var)/.cache)

pep8:
	pep8 .

autopep8:
	autopep8 . --recursive --in-place --pep8-passes 2000

lint:
	make pep8

lint-fix:
	make autopep8

test:
	py.test . --verbose

test_binfilepy:
	pytest ./tests/test_binfilepy.py -k test_binfilewriter -s
